In [6]:
import pandas as pd
import numpy as np

In [7]:
a=[2,3,4]
b=[4,7,9]
sum(a+b)

29

In [8]:
#to calculate individual summation we need to use numpy
np_a=np.array(a)
np_b=np.array(b)

In [9]:
np_a + np_b

array([ 6, 10, 13])

In [15]:
#Numpy Array only uses single data type otherwise changes to string if mixed
p=np.array([1,2,'abv'])
p

array(['1', '2', 'abv'], dtype='<U21')

In [16]:
#Bool values are converted to binary
q=np.array([1,5,True,False])
q

array([1, 5, 1, 0])

In [22]:
#Different arrays don't add up
# p+q

In [23]:
q.max()

5

In [24]:
q.mean()

1.75

In [25]:
q.min()

0

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.zeros(2)

array([0., 0.])

In [32]:
# Only normal multiplication can be performed
q*3

array([ 3, 15,  3,  0])

In [38]:
q*[2]

array([ 2, 10,  2,  0])

In [39]:
# Array_Broadcasting: Makes N-Dimen. array matching to initial array
# Helps in assigning weights to features
q*np.array([2.2])

array([ 2.2, 11. ,  2.2,  0. ])

In [40]:
# Different values cannot be broadcasted, either the N-D should be 1 or equal
# q*np.array([2.2,4.4])

In [41]:
# list functions work on n-d array
q

array([1, 5, 1, 0])

In [49]:
q[1]

5

In [42]:
q[1:]

array([5, 1, 0])

In [52]:
q_2d=np.array([[1,2],[3,4]])
q_2d

array([[1, 2],
       [3, 4]])

In [54]:
q_2d.sum()

10

In [55]:
# Axis 0 = Column
# Axis 1 =Row
q_2d.sum(axis=0)

array([4, 6])

In [58]:
# 2-d arrays are matrices, All above are tensors: 3-d,4-d tensors
# Matrices can be tranasposed
q_2d.transpose()
q_2d.T

array([[1, 3],
       [2, 4]])

In [67]:
# To generate identity matrix: np.eye(dimension)
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [60]:
# Can define ones and zeros in N-d
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [62]:
np.zeros([2,1])

array([[0.],
       [0.]])

In [70]:
q_2d

array([[1, 2],
       [3, 4]])

In [69]:
# Broadcaasting accross Matrices
q_2d+np.eye(2,1)

array([[2., 3.],
       [3., 4.]])

In [79]:
# Dot product can only be performed when dimension match i.r Col = Row
q_dot=q_2d.dot(np.ones([2,3]))
q_dot

array([[3., 3., 3.],
       [7., 7., 7.]])

In [80]:
q_2d.shape

(2, 2)

In [81]:
q_dot.shape

(2, 3)

In [113]:
# use random function to generate arrays
np_reshape=np.random.random(6)
np_reshape

array([0.0530658 , 0.00190293, 0.7890766 , 0.53614657, 0.06451744,
       0.68970859])

In [114]:
# Reshaping to match dimension of data: np.reshape(row,col)
# Use col = -1 if don't know dimension and give only rows
np_reshape.reshape(2,3)

array([[0.0530658 , 0.00190293, 0.7890766 ],
       [0.53614657, 0.06451744, 0.68970859]])

In [115]:
np_reshape.reshape(1,-1)

array([[0.0530658 , 0.00190293, 0.7890766 , 0.53614657, 0.06451744,
        0.68970859]])

In [116]:
# -----------------------------------------------------------------------------#
# To use Linear Algebra
import numpy.linalg as la

In [117]:
q_2d

array([[1, 2],
       [3, 4]])

In [118]:
# Inverse Matrix
la.inv(q_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [119]:
# Find Eigen Values
la.eig(q_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [120]:
np.random.shuffle(np_reshape)
np_reshape

array([0.7890766 , 0.68970859, 0.53614657, 0.06451744, 0.00190293,
       0.0530658 ])

In [121]:
# To generate b/w 0,1
np.random.rand(2,3)

array([[0.84286829, 0.43400762, 0.75776218],
       [0.29675287, 0.40785294, 0.58536792]])

In [122]:
# To generate b/w a range: randint(range,dim.)
np.random.randint(1,10,6)

array([1, 6, 9, 6, 1, 8])

In [124]:
# To generate between standard normal/binomial
np.random.randn(3,2)

array([[ 0.31734762, -0.35609054],
       [-1.93811439,  0.75639691],
       [-1.57717737,  1.15553198]])

In [130]:
# Find success with particular prob. in given trial using Binomial and which points succed
np.random.binomial(20,0.4,6)

array([ 7,  5,  8, 10,  9,  8])

In [132]:
#Exponential Distribution using lambda and no of points
np.random.exponential(0.7,5)

array([1.56170472, 0.87920063, 1.27351777, 0.22522876, 0.14067022])

In [133]:
# Use normal distribution using mean and std dev
np.random.normal(4,1.5,5)

array([4.47455062, 3.727578  , 4.93344602, 5.34680706, 2.02170535])

In [137]:
# Logistic Distribution
np.random.logistic(2,4,7)

array([-8.17667845, -7.10692543, -1.57500383, 11.55705426, 29.27254249,
       13.3334454 ,  4.87102741])

In [142]:
# To stack array over array: Enter in tuple
np.vstack((np_reshape.reshape(3,-1),q_2d))

array([[7.89076602e-01, 6.89708592e-01],
       [5.36146569e-01, 6.45174353e-02],
       [1.90292576e-03, 5.30657982e-02],
       [1.00000000e+00, 2.00000000e+00],
       [3.00000000e+00, 4.00000000e+00]])

In [144]:
np.hstack((np_reshape.reshape(2,-1),q_2d))

array([[7.89076602e-01, 6.89708592e-01, 5.36146569e-01, 1.00000000e+00,
        2.00000000e+00],
       [6.45174353e-02, 1.90292576e-03, 5.30657982e-02, 3.00000000e+00,
        4.00000000e+00]])

In [165]:
# Use %%time to find time taken for processes
%%time
q_2d+np.random.randint(1,65443,[2,2])

CPU times: user 1.19 ms, sys: 10 µs, total: 1.2 ms
Wall time: 1.22 ms


array([[45510, 16143],
       [41587,  1478]])

In [156]:
0